### ISSUE TITLE
No "ploidy_cells_list.tsv" in "meta"

### ISSUE THREAD

**Issue by JATC1024** [EngeLab/DNTRseq#1]
I tried to run the scripts using snakemake and received the error "File meta/ploidy_cells_list.tsv does not exist". It seems to me that there should be a file named "ploidy_cells_list.tsv" in the directory "meta"?

**Comment by JATC1024** [comment]
I was able to resolve this by running the rule "filter_ploidy_cells". It generated the file for me. Though I encounter a new problem: 

> KeyError in line 371 of /mnt1/hao/copykat/DNTRseq/Snakefile:
> 'rna_ref_dir'

It looks like there should be the field "rna_ref_dir" in the "config.yaml" file under "ref". Can I specify this myself and what should the content be?

**Comment by vasiliosz** [comment]
Hi, thanks for pointing this out. 
`rna_ref_dir` is the STAR reference index directory (from `—genomeDir` in STAR) . We’ll correct this and the ploidy file list
